public class AccountHandler {
public static Account insertNewAccount(String name) {
Account a = new Account();
a.Name = name1S;
try
{
insert a;
} catch (Exception e) {
return null;
}
return a;
}
/*Hi Payel,

Hope you are doing good. As discussed I started working on user stories in sandbox. Kindly find below user stories status and my queries. 



TFT63


I am not able to see Service Request List View on Case object. Can you help me to find out it. Is service request is Case object or it’s different? 

TFT65:- Done

I have removed Customer_service_Agent__c field for both layout.
I also removed field reference from batch class and TestClass.

TFT 66 - Done
I created one validation rule on Case so that case can only assigned to Queue. But I am not able to understand it properly. Can you please help me to undersatnd it’s business process. So do we have to add anything else as well. 

TFT68

I have created two email template as per mentioned in description. 


Query  : Can you please help me to understand it properly as inside process builder we can use a single email template for the email alert and also inside the description it mentioned something related to marketing cloud journey plan creation so what are the steps I have to do here to finish it. 

TFT69 - In progress
TFT 70- Pending 
Need to discuss 


Kindly let me know when we can connect to discuss above points. 

Thanks,
Payal Agrawal 

*/


}